### ISSUE TITLE
Where the FPGA accelerator simulator source code is?

### ISSUE THREAD

**Issue by un-knight** [yhhhli/BRECQ#10]
According to the paper appendix *B.4.3 latency acquisition*, the simulator is available in the provided source codes. But how can I find it? thx.

**Comment by yhhhli** [comment]
Sorry about this, we indeed uploaded the code in review stage, but we are not planning to release this part of the code right now since it belongs to sensetime research.

**Comment by touxinliang123** [comment]
it is a sad story.
