### ISSUE TITLE
What is the purpose for setting retain_graph=True?

### ISSUE THREAD

**Issue by un-knight** [yhhhli/BRECQ#12]
https://github.com/yhhhli/BRECQ/blob/2888b29de0a88ece561ae2443defc758444e41c1/quant/block_recon.py#L91

What is the purpose for setting `retain_graph=True`?

**Comment by KLONNEX** [comment]
Hello, @un-knight! When you train your model, the activations saves for each step to calculate gradiends. And they are stored until gradients are calculated (that is when you use err.backward() with default retain_graph=False). If you want to save calculated activations, you will set retain_grad=True.

**Comment by un-knight** [comment]
@KLONNEX thanks for telling me that!
