### ISSUE TITLE
How to deal with data parallel and distributed data parallel?

### ISSUE THREAD

**Issue by jang0977** [yhhhli/BRECQ#13]
On my eyes, your code is just running with single gpu while I need to test this code with multi-gpu for other implementations. I just want to check that you have ran your code using data parallel and distributed data parallel.

**Comment by yhhhli** [comment]
Good question, you cannot warp the model with data parallel functions
To support multi-GPU reconstruction, you should initialize distributed environments and allreduce the gradients manually.
I will add the dist mode in a few days.

**Comment by zjxyz** [comment]
@yhhhli 
hi，multi-GPU reconstruction does not reduce the time consumption. Is there any way to speed up reconstruction.
