### ISSUE TITLE
disable act quantization is designed for convolution 

### ISSUE THREAD

**Issue by zjxyz** [yhhhli/BRECQ#23]
Hi,
Very impressive coding.

There is a question about the quantization of activation values.

In the code:

# disable act quantization is designed for convolution before elemental-wise operation,
# in that case, we apply activation function and quantization after ele-wise op.

Why can it be replaced like this？

Thanks

**Comment by yhhhli** [comment]
I think some hardware backend support such type of computation graph. However, it doesn't fit all HW implementations, you can change the position of it if you want.

**Comment by zjxyz** [comment]
Thanks
