### ISSUE TITLE
搭建半天的环境，结果感情受到了伤害···

### ISSUE THREAD

**Issue by wangshankun** [yhhhli/BRECQ#24]
![image](https://user-images.githubusercontent.com/3970271/144569193-0ee6eba0-14fb-4fcc-9e95-6c7a9ec9d403.png)

**Comment by yhhhli** [comment]
请问这是什么模型以及什么数据集？

**Comment by wangshankun** [comment]
感谢回复，因为手里没有ILSVRC2012，我用的Tiny ImageNet ，就是上图结果；
周末两天下载了ILSVRC2012的var，代替train测试结果是可以的；

**Comment by yhhhli** [comment]
哦哦如果你是用的tinyimagenet和我提供的预训练模型那效果估计挺差的，因为需要再那上面单独训练一下。
如果你需要1024张训练集数据我可以保存一个numpy文件传给你。
