### ISSUE TITLE
激活值量化问题

### ISSUE THREAD

**Issue by liu-zhenhua** [yhhhli/BRECQ#27]
非常棒的工作，有一个小问题想请教一下~
在quant_block中有中间的激活层，但是在forward的时候没有使用，比如图中的conv1.activation_function
![image](https://user-images.githubusercontent.com/19202799/147544082-f51ad6a5-7e17-4dc9-b27b-f40217a15cc2.png)
![image](https://user-images.githubusercontent.com/19202799/147544211-d3264e05-5f7c-43ac-877e-a5543b3b1bd5.png)
期待您的回答~

**Comment by rainyBJ** [comment]
这个激活函数是conv1内部的，会在out=self.conv1(x)的forward函数中执行，对应quant_layer.py这一部分。
![image](https://user-images.githubusercontent.com/49946568/147625043-e85f90f8-c6ad-4525-9bd3-7295f1755bca.png)

**Comment by liu-zhenhua** [comment]
嗯嗯，看到了，多谢回复
