### ISSUE TITLE
权重更新范围限制

### ISSUE THREAD

**Issue by rainyBJ** [yhhhli/BRECQ#28]
想问一下雨杭大佬，你们有没有试过AdaQuant他们的方法，去掉权重更新的范围限制来进行重构呢？这样子理论上量化的效果是不是会有进一步提升？

**Comment by yhhhli** [comment]
其实这个问题AdaRound论文中已经讨论过了，结论是不如Round形式。
在AdaQuant论文中有效果可能是他们代码每层只finetune了400iters。所以round学习的不如ste那样。而AdaRound论文的实验finetune了一万iters。

![image](https://user-images.githubusercontent.com/44066452/147625844-78832aac-1b51-450c-b588-9756ee1e58c3.png)
![image](https://user-images.githubusercontent.com/44066452/147625873-4164760f-816e-493d-8b9c-28431d435b0b.png)

**Comment by rainyBJ** [comment]
好的，感谢！
