### ISSUE TITLE
8bit result？

### ISSUE THREAD

**Issue by yyfcc17** [yhhhli/BRECQ#3]
can you provide normal 8/8 bits quantization results of Resnet18 & mobilenetV2 on imagenet? since this is the most widely used version.

**Comment by yhhhli** [comment]
Hi,

Thanks for your comment, you can run the experiment by setting `--n_bits_a 8 --n_bis_w 8`, then you can get the following result:

`Full quantization (W8A8) accuracy: 71.01799774169922` for resnet18,
`Full quantization (W8A8) accuracy: 72.44599914550781` for mobilenetv2。

**Comment by yyfcc17** [comment]
Thank you very much!
