### ISSUE TITLE
channel_wise quantization

### ISSUE THREAD

**Issue by shiyuetianqiang** [yhhhli/BRECQ#4]
Hi, nice idea for quantizaton
But it seems that the paper(not include the appendix) did not point that it is channel-wise quantization. however, the code showed it is.
As we know, it is of course that channel-wise quntization would outperform layer-wise quantization.
So, maybe it's hard to say that the performance of your method is close to QAT

**Comment by yhhhli** [comment]
Hi there,

thanks for your problem, this is an interesting problem. 

For one thing, if you run our code you can find channel-wise weight quantization does not bring much improvement in 4bit quantization. ResNet W4A4 per-layer accuracy: 69.63, ResNet W4A4 per-channel accuracy: 69.20.

For another, your opinion that `it is of course that channel-wise quantization would outperform layer-wise quantization` is not always right. The SOTA QAT method, i.e. LSQ, actually often crashes in the per-channel quantization in our implementation. In fact, I haven't seen any per-channel quantization that can learn step size via gradient descent, it is highly possible that learnable methods are very unstable in per-channel settings. You can try it out and find some interesting experimental results if you implement LSQ in per-channel quantization. 

Thanks.
