### ISSUE TITLE
how to reproduce zero data result?

### ISSUE THREAD

**Issue by yyfcc17** [yhhhli/BRECQ#6]
as title.

there is a bug:
https://github.com/yhhhli/BRECQ/blob/da93abc4f7e3ef437b356a2df8a5ecd8c326556e/main_imagenet.py#L173

args.batchsize should be args.workers

**Comment by yhhhli** [comment]
Thanks,

**Comment by yyfcc17** [comment]
question not answered, how can i reproduce zero data result?
--num_samples 0 , will triger an error

**Comment by yhhhli** [comment]
Do you mean the ZeroQ dataset? 
I use the code from https://github.com/amirgholami/ZeroQ,
you can use that code to generate 1024 synthesized images

**Comment by yyfcc17** [comment]
in your paper, there are results of BRECQ without training data:
https://mmbiz.qpic.cn/mmbiz_png/n3Mr5TfFd0eXzicXVUfiau7CKNQrWiaJpibsjrXPVOXZqbsHsy2x8c4XKYFgo9eY1d3TqhffkrA9CXibA9mkysvQ0xw/640?wx_fmt=png&tp=webp&wxfrom=5&wx_lazy=1&wx_co=1

**Comment by yhhhli** [comment]
As I said, I use ZeroQ to generate 1024 synthesized images and then use them to perform BRECQ. You can find it in Section B.2
![image](https://user-images.githubusercontent.com/44066452/112780573-b2cba600-907b-11eb-9a3d-47106bfcdf85.png)
![image](https://user-images.githubusercontent.com/44066452/112780573-b2cba600-907b-11eb-9a3d-47106bfcdf85.png)

**Comment by yyfcc17** [comment]
oh, i see. thank you!
