### ISSUE TITLE
Cannot reproduce the accuracy

### ISSUE THREAD

**Issue by Mikezhang97** [yhhhli/BRECQ#7]
Greetings,

Really appreciate your open source contribution.

However, it seems the accuracy mentioned in the paper cannot be reproduced applying the standard Imagenet. For instance, with the full precision model, I have tested Resnet 18 (70.186%), MobileNetv2(71.618%), which is slightly lower than the results from your paper (71.08, 72.49 respectively).

Have you utilized any preprocessing techniques other than imagenet.build_imagenet_data?

Thanks

**Comment by yhhhli** [comment]
Hi, can you validate now? 

It seems there is a typo in my build_imagenet_data. Now I change the Resize((256, 256)) to Reszie(256)

**Comment by Mikezhang97** [comment]
> Hi, can you validate now?
> 
> It seems there is a typo in my build_imagenet_data. Now I change the Resize((256, 256)) to Reszie(256)

This would work, thanks a lot!
